### ISSUE TITLE
ionic serve报错了

### ISSUE THREAD

**Issue by chapgaga** [IonicChina/ioniclub#2]
准备在浏览器里跑,报错了,咋办?

ionic serve

Unable to locate the ionic.project file. Are you in your project directory? (CLI v1.4.5)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
OS: Windows 7 SP1
Node Version: v0.12.1

**Comment by donghongfei** [comment]
@chapgaga 你是不是没有进入到项目目录？
